services:
  frontend:
    build:
      context: ./frontend-demo
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - chromadb
    environment:
      - CHROMA_DB_HOST=chromadb
      - CHROMA_DB_PORT=8000

  chromadb:
    image: chromadb/chroma
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/.chroma/index

volumes:
  chroma_data: